### DISCUSSION TITLE
Apply role to already installed proxmox  machines

### DISCUSSION THREAD

**Discussion by matthew-on-git** [lae/ansible-role-proxmox#213] [Show and tell]
I was setting up a home lab and came across this beautiful repo with the exact things I was looking for. I had already installed proxmox on my 3 laptops, but this role is meant for debian OS. 
I was able to apply it any way, I believe, because I had already run the following on my machines. I hope this helps someone else.
```yml
#!/usr/bin/env ansible-playbook
---
- hosts: all
  tasks:
  ### Fix repos to free version
    - name: Delete pmx enterprise repo
      apt_repository:
        repo: 'deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise'
        state: absent
    - name: Enable free pmx repo
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription'
        state: present
```
and ...
```yml
#!/usr/bin/env ansible-playbook```#!/usr/bin/env ansible-playbook
---
- hosts: all
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
```

Also if you are using laptops like me, you can keep the lid from shutting them off with this:
```yml
#!/usr/bin/env ansible-playbook
---
- hosts: all
  tasks:
    - name: Config systemd not to sleep on lid shut
      ansible.builtin.template:
        src: etc/systemd/logind.conf.j2
        dest: /etc/systemd/logind.conf
        backup: true
        mode: 0644
        owner: root
        group: root
      notify:
        - reload_systemd
```
