### ISSUE TITLE
Define all hosts and pvelocalhost in /etc/hosts

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-proxmox#11]
From pve-user:

>  Each node should have all other nodes listed in the /etc/hosts
> files.  Currently, it only adds the local hostname to it.
>       Additionally,  the local node should add "pvelocalhost" to the
> /etc/hosts entry.  An example for a host of "10.0.0.2"
> 
> 10.0.0.1 mox1.example.com mox1
> 10.0.0.2 mox2.example.com mox2 pvelocalhost
> 10.0.0.3 mox3.example.com mox3
> ...

**Comment by ikus060** [comment]
Something similar to this should do the trick.
```
- name:
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }}"
  when: 'ansible_fqdn' in hostvars[item] and ansible_fqdn != hostvars[item]["ansible_fqdn"]
  with_items: "{{ groups[pve_group] }}"
```
