### ISSUE TITLE
The problem with adding nodes to the pve cluster

### ISSUE THREAD

**Issue by artemoz2021** [lae/ansible-role-proxmox#138]
Hello.

I'm faced with the following issue: I have an existing pve cluster (deployed by this role). When i'm trying to add a new node to this cluster, the **add node to the cluster** task fails but returned the changed state, so the role execution is not stopped.
There is the verbose output from this task:

```
TASK [lae.proxmox : Add node to Proxmox cluster] *************************************************************************************************************
task path: /Users/artem/.ansible/roles/lae.proxmox/tasks/pve_add_node.yml:6
Using module file /Users/artem/git/proxmox/.venv/lib/python3.8/site-packages/ansible/modules/commands/command.py
Pipelining is enabled.
<pveinfra323> ESTABLISH SSH CONNECTION FOR USER: artem
<pveinfra323> SSH: EXEC ssh -o ForwardAgent=yes -o ControlMaster=no -o ControlPersist=60s -o PreferredAuthentications=publickey -o ServerAliveInterval=45 -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="artem"' -o ConnectTimeout=10 -o ControlPath=/Users/artem/.ansible/cp/%h-%p-%r pveinfra323 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-vddkkgomvuibyjocbvufowwifprhzsoq ; /usr/bin/python3.7'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<pveinfra323.h.o3.ru> (0, b'\n{"cmd": ["pvecm", "add", "100.80.7.2", "-use_ssh", "-link0", "100.80.7.12", "-link1", "192.168.0.105"], "stdout": "", "stderr": "unable to copy ssh ID: exit code 1", "rc": 0, "start": "2021-06-11 08:53:26.315116", "end": "2021-06-11 08:53:26.817752", "delta": "0:00:00.502636", "changed": true, "invocation": {"module_args": {"creates": "/etc/pve/corosync.conf", "_raw_params": "pvecm add 100.80.7.2 -use_ssh -link0 100.80.7.12  -link1 192.168.0.105 ", "warn": true, "_uses_shell": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "removes": null, "stdin": null}}}\n', b'')
changed: [pveinfra323] => changed=true 
  cmd:
  - pvecm
  - add
  - 100.80.7.2
  - -use_ssh
  - -link0
  - 100.80.7.12
  - -link1
  - 192.168.0.105
  delta: '0:00:00.502636'
  end: '2021-06-11 08:53:26.817752'
  invocation:
    module_args:
      _raw_params: 'pvecm add 100.80.7.2 -use_ssh -link0 100.80.7.12  -link1 192.168.0.105 '
      _uses_shell: false
      argv: null
      chdir: null
      creates: /etc/pve/corosync.conf
      executable: null
      removes: null
      stdin: null
      stdin_add_newline: true
```

If i run the role a second time - the node will be successfully added to the cluster.
Any ideas why the nodes added on a second run of the role only?
