### ISSUE TITLE
PVE 7 support

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-proxmox#143]
I think I recall seeing an email saying PVE 7 was released (or at least an RC came out), so I'd like to work on supporting it in this role. However, per current circumstances (which I also alluded to in https://github.com/lae/ansible-role-netbox/issues/132) I probably won't be able to get to this for several months. I also haven't been gainfully employed/haven't had access to bare metal environments since 2018, so I can't really experiment/test a few things effectively (Ceph being one) without using something like Packet.

Also with PVE 7, I think we can sunset support for PVE 5/Debian Stretch since they're EOL (but I don't think this means much code cleanup like we had with PVE 4).

Anyway, if there is anyone who wants to get a headstart and work on getting this role working with 7, please feel free to start a branch (if I've already made you a collaborator) or fork this repo+create a new feature branch and open a PR. If discussion is needed, you can use this thread.

**Comment by zenntrix** [comment]
I have created a feature branch for this work 'feature/pve7'

**Comment by trickert76** [comment]
Ah, great. I've started to think about the migration process yesterday and now I see - there is already an open ticket. In production I'm waiting for Debian Bullseye to be official released - just to be sure.

Some questions. I see, you already did added the most necessary changes to the repo for PVE7. I think, most of it is the same I did last time with PVE6. Did you tested the installation process?

Main question is: I'm not 100% sure - do you think, this steps are also useful in case of "upgrade". I've always installed new major versions in the past. After reading the upgrade guide I think your changes are enough (adding key, switching apt-source-list, apt dist-upgrade). But I'm not sure. I'm thinking about some kind of "upgrade detection" during a play. Is the existing installation older then run pve6to7 (or later pve7to8), check that and then stop all VMs if configured and upgrade.

I can try to run the play on two single servers, but I don't have a test-cluster at the moment. Only a productive cluster (upgrading it will be fun).

**Comment by trickert76** [comment]
Ah, sorry - the last commit was wrong - I wanted to merge the pve7 branch to my local branch - but it was commited vice verse.

**Comment by zenntrix** [comment]
I have been testing the installation process as fresh install using my test servers and i have also tested a partial update so far where i upgrade the OS to bullseye manually and then use Ansible to upgrade pve6to7. 

My next stage is to try and upgrade from 6to7 fully using just this ansible but before then i am experiencing so excessive performance issues of VMs on PVE7 so i would advise upgrading at the moment. 

The other thing to consider if doing an ansible upgrade is the highlighted issue of potential mac address changes when going from 6 to 7.

**Comment by trickert76** [comment]
Upgrading OS, later Proxmox works? Based on the upgrade guide, the PVE repo must be switched too. I'm trying that at the moment manually on a test machine, to have a look of the changes.

I've started to add some tasks for an explicit upgrade from x to bullseye like:

```
---
- name: Gather distribution specific variables
  include_vars: "debian-{{ pve_upgrade_distribution }}.yml"

- name: "Switching distribution from {{ ansible_distribution_release }} to {{ pve_upgrade_distribution }}"
  copy:
    backup: true
    dest: "/etc/apt/sources.list"
    content: |
      # {{ ansible_managed }}
      deb http://deb.debian.org/debian bullseye main
      deb-src http://deb.debian.org/debian/ bullseye main
      deb http://security.debian.org/debian-security bullseye-security main
      deb-src http://security.debian.org/debian-security bullseye-security main
      deb http://deb.debian.org/debian bullseye-updates main
      deb-src http://deb.debian.org/debian/ bullseye-updates main

- name: "Trust Proxmox' packaging key"
  apt_key:
    data: "{{ lookup('file', pve_release_key) }}"
    id: "{{ pve_release_key_id }}"
    state: "present"

- name: "Add Proxmox repository"
  apt_repository:
    repo: "deb {{ pve_repository }} {{ pve_upgrade_distribution }} {{ pve_subscription }}"
    filename: "proxmox"
    state: "present"
  register: _pve_repo

- name: "Add Proxmox Ceph repository"
  apt_repository:
    repo: "{{ pve_ceph_repository_line }}"
    filename: "ceph"
    state: "present"
  register: _pve_ceph_repo
  when: "pve_ceph_enabled | bool"


- name: "Run apt-get dist-upgrade on repository changes"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: "dist"
  when: "_pve_repo is changed or _pve_ceph_repo is changed"
  retries: 2
  register: _dist_upgrade
  until: "_dist_upgrade is succeeded"

- name: "Reboot for kernel update"
  reboot:
    msg: "PVE kernel update detected by Ansible"

- name: "Gather new facts"
  setup:
```

This would be a new file that is called at start of main.yml with

```
- name: "Upgrade system"
  include_tasks: "upgrade_system_{{ pve_upgrade_distribution }}.yml"
  when:
    - "pve_upgrade_distribution is defined"
    - "pve_upgrade_distribution != ansible_distribution_release"
```

And the new default vars:

```
pve_subscription: "pve-no-subscription"
pve_repository: "http://download.proxmox.com/debian/pve"
pve_upgrade_distribution: "bullseye"
```

For that `pve_repository_line` is replaced with `deb {{ pve_repository }} {{ ansible_distribution_release }} {{ pve_subscription }}`
