### ISSUE TITLE
Detect sshd service name or make configurable

### ISSUE THREAD

**Issue by aarononeal** [lae/ansible-role-proxmox#187]
Handler:
```yaml
- name: reload sshd configuration
  service:
    name: sshd
    state: reloaded
```

Fails with:
`Could not find the requested service sshd: host`

On distros where the service name is `ssh`.
