### ISSUE TITLE
Unable to create pve_storages using example data

### ISSUE THREAD

**Issue by JohanLeirnes** [lae/ansible-role-proxmox#214]
```yaml
   - name: ceph1
     type: rbd
     content: [ "images", "rootdir" ]
     nodes: [ "proxmox-01-node-01.local", "proxmox-01-node-02.local", "proxmox-01-node-03.local" ]
     username: nvadmin
     pool: hdd
     krbd: yes
     monhost:
       - 192.168.1.241
       - 192.168.1.242
       - 192.168.1.243
   - name: cephfs1
     type: cephfs
     content: [ "snippets", "vztmpl", "iso"  ]
     nodes: [ "proxmox-01-node-01.local", "proxmox-01-node-02.local", "proxmox-01-node-03.local" ]
     username: nvadmin
     monhost:
       - 192.168.1.241
       - 192.168.1.242
       - 192.168.1.243
```
       
 When i use this code i get this error while running it.
 
 `failed: [proxmox-01-node-01] (item={'name': 'ceph1', 'type': 'rbd', 'content': ['images', 'rootdir'], 'nodes': ['proxmox-01-node-01.local', 'proxmox-01-node-02.local', 'proxmox-01-node-03.local'], 'username': 'nvadmin', 'pool': 'hdd', 'krbd': True, 'monhost': ['192.168.1.241', '192.168.1.242', '192.168.1.243']}) => {"ansible_loop_var": "item", "changed": false, "item": {"content": ["images", "rootdir"], "krbd": true, "monhost": ["192.168.1.241", "192.168.1.242", "192.168.1.243"], "name": "ceph1", "nodes": ["proxmox-01-node-01.local", "proxmox-01-node-02.local", "proxmox-01-node-03.local"], "pool": "hdd", "type": "rbd", "username": "nvadmin"}, "msg": "nodes: invalid format - value does not look like a valid node name\n", "name": "ceph1"}`
 
 `failed: [proxmox-01-node-01] (item={'name': 'cephfs1', 'type': 'cephfs', 'content': ['snippets', 'vztmpl', 'iso'], 'nodes': ['proxmox-01-node-01.local', 'proxmox-01-node-02.local', 'proxmox-01-node-03.local'], 'username': 'nvadmin', 'monhost': ['192.168.1.241', '192.168.1.242', '192.168.1.243']}) => {"ansible_loop_var": "item", "changed": false, "item": {"content": ["snippets", "vztmpl", "iso"], "monhost": ["192.168.1.241", "192.168.1.242", "192.168.1.243"], "name": "cephfs1", "nodes": ["proxmox-01-node-01.local", "proxmox-01-node-02.local", "proxmox-01-node-03.local"], "type": "cephfs", "username": "nvadmin"}, "msg": "nodes: invalid format - value does not look like a valid node name\n", "name": "cephfs1"}`
 
 nodes: invalid format?
