### ISSUE TITLE
Ceph: ceph-volume lvm batch support

### ISSUE THREAD

**Issue by junousi** [lae/ansible-role-proxmox#225]
This is part feature request part reminder for myself as I could probably whip up a PR at some point.

According to The Literature (1*, 2*) throwing a DB/WAL to an NVMe might not be the only way to utilize an NVMe. But, when storing data, it might be sub-optimal to have the OSD span the entire device - it is better to split it at least a little bit.

Enter LVM batches:

A) `ceph-volume lvm batch --osds-per-device 4 /dev/nvme2n1`

or with separate DB

B) `ceph-volume lvm batch --osds-per-device 4 /dev/nvme2n1 --db-devices /dev/nvme0n1`

or with multiple data cards

C) `ceph-volume lvm batch --osds-per-device 4 /dev/nvme2n1 /dev/nvme3n1 --db-devices /dev/nvme0n1`

I suppose the input data could look something like:

```
pve_ceph_osds:
  # current form factor
  - device: /dev/sdc
  # proposed form factor 
  - lvm_batch:
      osds_per_device: 4
      devices:
        - /dev/nvme2n1
        - /dev/nvme3n1
      db_devices:
        - /dev/nvme0n1
```

...but up for debate of course.

I have tested scenario A) by running the command manually server-side, then adding just `- device /dev/nvme2n1` into `pve_ceph_osds` then running playbook. Works fine. This is on latest PVE, Ceph quincy, latest version of the role. But it would be handy to have the role control the batch creation, hence writing up this Issue.

IIUC when offloading DB to a dedicated device, once a batch is built there will be no possibility to add more devices later on as all of the DB device space will be used entirely and split evenly upon build time. So a device add would probably mean a teardown + rebuild for the entire batch. Meaning better have spare cluster capacity for such scenarios.

---

1* https://forum.proxmox.com/threads/recommended-way-of-creating-multiple-osds-per-nvme-disk.52252/
2* https://www.reddit.com/r/ceph/comments/jnyxgm/how_do_you_create_multiple_osds_per_disk_with/

**Comment by lae** [comment]
Sounds like a good idea.

Some suggestions for implementation using the suggested schema (but should still apply in any case):

- `pve_ceph_osds[*].device` entries should still remain valid/functional
- there should be an early role variable check to ensure devices in `pve_ceph_osds[*].lvm_batch.devices[*]` and `pve_ceph_osds[*].device` are all unique/don't overlap

I think, ideally, if we're going to mix use of `pveceph` and `ceph-volume` for OSD management, that we should switch to writing a module for it, since it should be easier to safely reason about actions and idempotency with python rather than using `set_fact` and all that<sup>0</sup>. But I guess adding a task prior to `Create Ceph OSDs` for lvm batch entries and then producing a list for the `Create Ceph OSDs` task could be one method? (if I'm understanding the procedure you describe correctly)

Hm...

After skimming through The Literature<sup>1</sup>, I'm wondering if trying to interface over `lvm batch` may be unnecessary, or rather should be its own exclusive role variable/task that is used to generate a list of OSDs and values for flags<sup>2</sup> to pass to `ceph-volume`/`pveceph`. The idempotency aspect<sup>3</sup> from `ceph-volume lvm batch` seems like it might be useful to interface over, too, and it looks like you could "plan" to have more data devices by specifying `--(block-db|block-wal|journal)-slots` to some expected number of devices when using batch.

Anyway, the reason why I think it might be unnecessary is that...the following seems to suggest `osds_per_device` just specifies a worker count for accessing a device rather than physically splitting it?

> Number of osd daemons per “DATA” device. To fully utilize nvme devices multiple osds are required. Can be used to split dual-actuator devices across 2 OSDs, by setting the option to 2.<sup>4</sup>

Which seems to suggest to me that maybe there's another way of configuring it outside of using lvm batch. But given the general benefits from lvm batch, might as well use it. Alternatively...drive groups<sup>5</sup> but I feel like that would definitely be pushing the scope of this role. 😅

I'll think about it some more but if you open a PR I'll take a look and evaluate.

<sup>0</sup> https://github.com/lae/ansible-role-proxmox/blob/develop/tasks/ceph.yml#L39
<sup>1</sup>: https://docs.ceph.com/en/latest/ceph-volume/lvm/batch/
<sup>2</sup>: https://docs.ceph.com/en/latest/ceph-volume/lvm/batch/#json-reporting
<sup>3</sup>: https://docs.ceph.com/en/latest/ceph-volume/lvm/batch/#idempotency-and-disk-replacements
<sup>4</sup>: https://docs.ceph.com/en/latest/cephadm/services/osd/#ceph.deployment.drive_group.DriveGroupSpec.osds_per_device
<sup>5</sup>: https://docs.ceph.com/en/latest/cephadm/services/osd/#drivegroups

**Comment by junousi** [comment]
> After skimming through The Literature1, I'm wondering if trying to interface over lvm batch may be unnecessary

It absolutely can be, and rather than trying to implement something asap I think it's a good idea to let this Issue brew for a while in case other ceph users would want to give feedback.

For example, simply augmenting support for the `pveceph osd ... -db_size` would probably allow similar control over the DB grain sizes. In similar fashion, I think some LVM wrapper/boilerplate could be considered towards a pveceph-only solution for partitioning the NVMe. It's irritatingly convenient that `ceph-volume` seems to do all these things automagically :)

Thanks for the schema pointers, I was also contemplating:

```
pve_ceph_osds:
  # current form factor
  - device: /dev/nvme2n1
    lvm_batch: true
    osds_per_device: 4
      devices:
        - 
        - /dev/nvme3n1
      db_devices:
        - /dev/nvme0n1
```

**Comment by junousi** [comment]
> After skimming through The Literature1, I'm wondering if trying to interface over lvm batch may be unnecessary

It absolutely can be, and rather than trying to implement something asap I think it's a good idea to let this Issue brew for a while in case other ceph users would want to give feedback.

For example, simply augmenting support for the `pveceph osd ... -db_size` parameter would probably allow similar control over the DB grain sizes. In similar fashion, I think some LVM wrapper/boilerplate could be considered towards a pveceph-only solution for partitioning the data part. It's irritatingly convenient that `ceph-volume` seems to do all these things automagically :)

Thanks for the schema pointers. I was also contemplating something like:

```
pve_ceph_osds:
  - device: /dev/nvme2n1
    block.db: /dev/nvme0n1
    lvm_batch: true
    osds_per_device: 4
  - device: /dev/nvme3n1
    block.db: /dev/nvme0n1
    lvm_batch: true
    osds_per_device: 4
```

...which would retain more of the existing structure, but needlessly replicate information.

And as well something like:

```
pve_ceph_osds:
  - device: /dev/nvme2n1
    lvm_batch: LABEL
pve_ceph_osds_batches:
  - LABEL:
      osds_per_device: 4
      block.db: /dev/nvme0n1
```

...which I suppose can get a bit hairy in other ways.
