### ISSUE TITLE
Ansible Linting

### ISSUE THREAD

**Issue by willifehler** [lae/ansible-role-proxmox#238]
Hi there,

thank you so much for this wonderful role. Please keep it going.

I have a feature request:
It would make sense to use ansible and yaml linting.

Just an example. It would make sense to use the fqcn here. (ansible.builtin.copy)

```
- name: Configure datacenter.cfg
  copy:
    dest: "/etc/pve/datacenter.cfg"
    owner: "root"
    group: "www-data"
    mode: "0640"
    content: |
      {% for k,v in pve_datacenter_cfg.items() %}
      {{ k }}: {{ v }}
      {% endfor %}
  when:
    - "not pve_cluster_enabled | bool or (pve_cluster_enabled | bool and inventory_hostname == _init_node)"
    - "pve_datacenter_cfg | length > 0"
```

Cheers - Willi
