### ISSUE TITLE
Add pinning of proxmox-default-kernel

### ISSUE THREAD

**Issue by btravouillon** [lae/ansible-role-proxmox#243]
We had some issues with the latest kernel 6.8 shipped with Proxmox 8.2.

These issues were somewhat expected as per https://pve.proxmox.com/wiki/Roadmap#Kernel_6.8. Proxmox proposal is to " create a file in `/etc/apt/preferences.d/proxmox-default-kernel` with the following content." to use the previous kernel 6.5.

```
Package: proxmox-default-kernel
Pin: version 1.0.1
Pin-Priority: 1000
```

We implemented a pre-task in our playbook, however, it would be nice to support such feature in the proxmox role.

I should be able to create a PR soon, but since I'm quite busy this week, I file this feature request (to not forget). Feel free to assign this ticket to me. :wink: 

```
    # Workaround
    - name: Pin the Proxmox kernel
      ansible.builtin.copy:
        content: |
          Package: proxmox-default-kernel
          Pin: version {{ pve_pin_default_kernel }}
          Pin-Priority: 1000
        dest: /etc/apt/preferences.d/proxmox-default-kernel
        mode: 0644
      when: pve_pin_default_kernel is defined
```
