### ISSUE TITLE
Add PVE LVM Storage

### ISSUE THREAD

**Issue by willifehler** [lae/ansible-role-proxmox#253]
Hey there,

is it already possible to add a local LVM storage?

```
pve_storages:
  - name: locallvm
     type: lvm
     content: [ "images", "iso" ]
     vgname: vg01
     path: /dev/sdb
```

```
"unexpected property 'path'
```

Cheers - Willi
