### ISSUE TITLE
"list index out of range" error in proxmox_group module

### ISSUE THREAD

**Issue by sseide** [lae/ansible-role-proxmox#53]
Hello,

i tried to install an proxmox stand-alone cluster using your role (v1.4.2 via ansible-galaxy) and run into an error on group management.

```
TASK [lae.proxmox : Configure Proxmox groups] ******************************************************************************************
failed: [host.local] (item={u'comment': u'Operations Team', u'name': u'ops'}) => 
{"ansible_loop_var": "item", "changed": false,
 "item": {"comment": "Operations Team", "name": "ops"},
 "module_stderr": "Shared connection to host.local closed.\r\n", 
 "module_stdout": "Traceback (most recent call last):\r\n
  File \"/root/.ansible/tmp/ansible-tmp-1557841838.09-250907062164291/AnsiballZ_proxmox_group.py\", line 114, in <module>\r\n
    _ansiballz_main()\r\n
  File \"/root/.ansible/tmp/ansible-tmp-1557841838.09-250907062164291/AnsiballZ_proxmox_group.py\", line 106, in _ansiballz_main\r\n
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n
  File \"/root/.ansible/tmp/ansible-tmp-1557841838.09-250907062164291/AnsiballZ_proxmox_group.py\", line 49, in invoke_module\r\n
    imp.load_module('__main__', mod, module, MOD_DESC)\r\n
  File \"/tmp/ansible_proxmox_group_payload_dXdbIL/__main__.py\", line 175, in <module>\r\n
  File \"/tmp/ansible_proxmox_group_payload_dXdbIL/__main__.py\", line 154, in main\r\n
  File \"/tmp/ansible_proxmox_group_payload_dXdbIL/__main__.py\", line 87, in create_group\r\n
  File \"/tmp/ansible_proxmox_group_payload_dXdbIL/ansible_proxmox_group_payload.zip/ansible/module_utils/pvesh.py\", line 86, in create\r\n
  File \"/tmp/ansible_proxmox_group_payload_dXdbIL/ansible_proxmox_group_payload.zip/ansible/module_utils/pvesh.py\", line 32, in run_command\r\nIndexError: list index out of range\r\n",
 "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
 "rc": 1}
```
Ansible playbook rrole configuration was:
```
    - role: lae.proxmox
      pve_group: proxmox
      pve_cluster_enabled: false
      pve_reboot_on_kernel_update: true
      pve_ssl_letsencrypt: true       # needs role systemli.letsencrypt
      pve_groups:
        - name: ops
          comment: Operations Team
```
I tried to install debian package for proxmox 5.4-1 (pve-no-subscription) on debian 9.9 with latest updates.

Another thnig i noticed was that the role was hanging at the installation step of proxmox deb packages at "/usr/bin/perl /usr/sbin/needrestart" - the deb installation step did not return and seem to wait on user interaction.
