### ISSUE TITLE
[Proxmox 5.4] storage type "Snippets" missing

### ISSUE THREAD

**Issue by sseide** [lae/ansible-role-proxmox#55]
using the ansible module and variable `pve_storage` i am able to create new storage spaces.
The default storage added by proxmox 5.4 (named 'local') has one addtionial type "Snippets" available besides "ISO Image", "Container" and so on...

Content types listed in the WebUI for the auto-created storage "local":
> Content: Disk image, ISO image, Container, Snippets, Container template

For my test i added all types listed inside proxmox_storage module as `content`, but "Snippets" is missing then.

https://github.com/lae/ansible-role-proxmox/blob/b1ea4297578357026161719d6fdeba682e18eacd/library/proxmox_storage.py#L37-L41

The ansible playbook has the following variable:
```
      pve_storages:
        - name: localdir
          type: dir
          content: [ "images", "rootdir", "vztmpl", "backup", "iso" ]
          path: /home/proxmox
          maxfiles: 4
```
This creates the following list as seen inside WebUI for storage "localdir":
> Content: VZDump backup file, Disk image, ISO image, Container, Container template

**Comment by lae** [comment]
Skimming through the `proxmox_storage` module source, it doesn't look like it actually restrict your choices to the ones listed in the documentation. Are you able to add `snippets` to your playbook and see if it works?

**Comment by sseide** [comment]
ok, thought this list is used to check if values are valid.

retried with "snippets" works and WebUI now lists this too as content type
```
      pve_storages:
        - name: localdir
          type: dir
          content: [ "images", "rootdir", "vztmpl", "backup", "iso", "snippets" ]
          path: /home/proxmox
          maxfiles: 4
```
Maybe adding it as a choice at the documentation or module may help others to get all possible values.

Thanks.
