### ISSUE TITLE
Create keyring for rbd pool in /etc/pve/priv/ceph

### ISSUE THREAD

**Issue by zenntrix** [lae/ansible-role-proxmox#84]
Whilst it is possible to create a pve_storage that points to an ceph rbd:
```
pve_storages:
  - name: vm-storage
    type: rbd
    content:
    - images
    - rootdir
    pool: vm-storage
    username: admin
    monhost:
    - proxmox-test.corp.zenntrix.com:6789
    - test-box.corp.zenntrix.com:6789
pve_ceph_pools:
  - name: vm-storage
    pgs: 64
    application: rbd
    storage: true
    rule: hdd
```

It is inaccessible due to the keyring not being created. I have only tried this with cephx, i believe it wouldn't be a problem without it.
